### ISSUE TITLE
Payable functions should include a value field

### ISSUE THREAD

**Issue by banteg** [wslyvh/contraktor#10]
A user should be able to attach an eth value if the function is marked as `payable`.

Example: `swapExactETHForTokens` in UniswapRouter
https://contraktor.netlify.app/contracts/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D

**Comment by wslyvh** [comment]
Fixed.

Also note that the app is accessible on an actual domain now...
https://ethcontract.watch/contracts/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D
