### ISSUE TITLE
Functions with no args aren't executable

### ISSUE THREAD

**Issue by banteg** [wslyvh/contraktor#3]
See this contract for example
https://contraktor.netlify.app/contracts/0xBa37B002AbaFDd8E89a1995dA52740bbC013D992

**Comment by wslyvh** [comment]
You mean the function row doesn't collapse, right?

Will try to allocate some time next week to fix it. Thanks for reporting!

**Comment by wslyvh** [comment]
PR #5 @rudygt merged. Should be fixed.  

But in all honesty, I haven't tested yet. I didn't have a suitable contract for it.

**Comment by wslyvh** [comment]
Closing issue
