### ISSUE TITLE
Show data type

### ISSUE THREAD

**Issue by calebsheridan** [wslyvh/contraktor#4]
The current state shows variable names and values. It would also be useful to see the data type (e.g. uint256) in secondary text.

**Comment by wslyvh** [comment]
Makes sense. That would be more aligned with its other members/functions, I guess.

**Comment by wslyvh** [comment]
Fixed. See for example:
https://ethcontract.watch/contracts/0x68c3d3877d8d218df2d885e15146d062c60b715b
