### ISSUE TITLE
USDt main contract is incorrect

### ISSUE THREAD

**Issue by gasolin** [wslyvh/contraktor#6]
The current link to the USDt main contract address is wrong
https://ethcontract.watch/contracts/0xdAC17F958D2ee523a2206206994597C13D831ec7

It shows an Upbit hack address report by https://portal.sentinelprotocol.io/indicator/5530e703-38d8-40eb-8d9a-a449496f9f4d

the real one is https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by wslyvh** [comment]
Hi, thanks for contributing!
 
Strange to see it linked to a hack, but can imagine USDt is commonly used to transfer in/out funds, even after hacks. 
The addresses were the same but I did merge your PR as I figured it made sense to align with Tether's site. 
But reading MyCrypto's article it seems uppercased (checksummed) is actually preferred.
