### ISSUE TITLE
fail to query with address[] in Views

### ISSUE THREAD

**Issue by gasolin** [wslyvh/contraktor#9]
ex https://ethcontract.watch/contracts/0x571C62a1c863aEAD01c1d34D8cB3Ee2c6f938800

![Imgur](https://i.imgur.com/Ml3JYqC.png)

enter `0xeb31973e0febf3e3d7058234a5ebbae1ab4b8c23`, `[0xeb31973e0febf3e3d7058234a5ebbae1ab4b8c23]`, `'0xeb31973e0febf3e3d7058234a5ebbae1ab4b8c23'`, or `['0xeb31973e0febf3e3d7058234a5ebbae1ab4b8c23']` not work

In etherscan readContract, enter `0xeb31973e0febf3e3d7058234a5ebbae1ab4b8c23` and query works
https://etherscan.io/address/0x571C62a1c863aEAD01c1d34D8cB3Ee2c6f938800#readContract

**Comment by wslyvh** [comment]
Will look into this next week. Thanks for reporting!

**Comment by wslyvh** [comment]
Fixed
